UniversityProject/Controllers/StudentController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using UniversityProject.DAL;
using UniversityProject.Models;
using UniversityProject.Models.ViewModels;

namespace UniversityProject.Controllers
{
    [Authorize(Roles = "Admin")]
    public class StudentController : Controller
    {
        UniversityDbContext db;

        public StudentController()
        {
            db = new UniversityDbContext();
        }

        [HttpGet]
        public ActionResult Index()
        {
            List<Student> model = db.Student.ToList();

            return View(model);
        }

        public ActionResult Create()
        {
            LoadFieldSelecttList();

            return View();
        }

        [HttpPost]
        public ActionResult Create(Student entity)
        {
            if (!ModelState.IsValid)
            {
                ViewBag.Message = "Inputs are NOT Correct";
                LoadFieldSelecttList();
                return View(entity);
            }

            //Add to database
            db.Student.Add(entity);
            db.SaveChanges();

            return RedirectToAction("Index");
        }

        public ActionResult Edit(int id)
        {
            LoadFieldSelecttList();

            Student entity = db.Student.Find(id);

            return View(entity);
        }

        [HttpPost]
        public ActionResult Edit(Student entity)
        {
            if (!ModelState.IsValid)
            {
                ViewBag.Message = "Inputs are NOT Correct";
                LoadFieldSelecttList();
                return View(entity);
            }

            db.Entry(entity).State = System.Data.Entity.EntityState.Modified;
            db.SaveChanges();

            return RedirectToAction("Index");
        }

        public ActionResult Delete(string StudentCode)
        {
            Student entity = db.Student.Where(x => x.StudentCode == StudentCode).FirstOrDefault();

            if (entity != null)
                db.Student.Remove(entity);

            db.SaveChanges();

            return RedirectToAction("Index");
        }

        public ActionResult P_Details(int id)
        {
            Student model = db.Student.Find(id);

            return PartialView(model);
        }

        [HttpPost]
        public ActionResult P_Create(Student entity)
        {
            db.Student.Add(entity);

            db.SaveChanges();

            return Json(new { message ="Student saved successfuly." });
        }

        private void LoadFieldSelecttList()
        {
            List<Field> fields = db.Field.ToList();

            List<SelectListItem> listItems = new List<SelectListItem>();

            foreach (var item in fields)
            {
                listItems.Add(new SelectListItem()
                {
                    Text = item.Caption,
                    Value = item.Id.ToString()
                });
            }

            ViewBag.FieldSelectList = listItems;
        }

        public ActionResult Test()
        {
            Student model = new Student()
            {
                FirstName = "Yashar",
                LastName = "Gorgani",
                StudentCode = "8615789"
            };

            return View(model);
        }
    }
}

UniversityProject/Controllers/TeacherController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using UniversityProject.DAL;
using UniversityProject.Models;
using UniversityProject.Models.ViewModels;

namespace UniversityProject.Controllers
{
    [Authorize(Roles ="Admin")]
    public class TeacherController : Controller
    {
        UniversityDbContext db;

        public TeacherController()
        {
            db = new UniversityDbContext();
        }

        // GET: Teacher
        public ActionResult Index()
        {
            var model = db.Teachers.ToList();

            return View(model);
        }

        public ActionResult Create()
        {
            LoadFieldSelecttList();
            return View();
        }

        [HttpPost]
        public ActionResult Create(TeacherCreateViewModel entity)
        {
            var teacher = new Teacher()
            {
                FirstName = entity.FirstName,
                LastName = entity.LastName
            };

            foreach (var id in entity.FieldIdList)
            {
                var field = db.Field.Find(id);

                teacher.Fields.Add(field);
            }

            db.Teachers.Add(teacher);

            db.SaveChanges();

            return RedirectToAction("Index");
        }

        private void LoadFieldSelecttList()
        {
            List<Field> fields = db.Field.ToList();

            List<SelectListItem> listItems = new List<SelectListItem>();

            foreach (var item in fields)
            {
                listItems.Add(new SelectListItem()
                {
                    Text = item.Caption,
                    Value = item.Id.ToString()
                });
            }

            ViewBag.FieldSelectList = listItems;
        }
    }
}

UniversityProject/Views/Shared/P_Header.cshtml
<div class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                @if (User.IsInRole("Admin"))
                {
                    <li>@Html.ActionLink("Students", "Index", "Student")</li>
                }
                @if (User.IsInRole("Admin"))
                {
                    <li>@Html.ActionLink("Teachers", "Index", "Teacher")</li>
                }
            </ul>
        </div>
    </div>
</div>

UniversityProject/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
</head>
<body>
    
    @Html.Partial("P_Header")

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
    @RenderSection("Scripts", false)
</body>
</html>